# Set the left half as the central device
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Tell the central that it should only expect 1 peripheral (the right half)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

# Enable ZMK Studio (Live Keymap Editing) over USB for the left half
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# (Optional) Enable display if your left half uses one
# CONFIG_ZMK_DISPLAY=y
