# =========================================================
# ZMK Studio (Live Keymap Editing)
# =========================================================
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# =========================================================
# Sleep Configuration
# =========================================================
CONFIG_ZMK_SLEEP=y
