include:
  - board: xiao_ble//zmk
    shield: totem_left
  - board: xiao_ble//zmk
    shield: totem_right
  - board: xiao_ble//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: prospector_adapter totem_dongle
    snippet: zmk-usb-logging

